module.exports = {
  FILE_PATTERN: '/**/*.js',
  DEFAULT_TITLE: 'CInspector',
  DEFAULT_OUTPUT_DIR: 'reports',
  DEFAULT_HEALTHY_INDEX: 60,
  DEFAULT_HEALTHY_SLOC: 300,
  DEFAULT_HEALTHY_COMPLEXITY: 10,
};
